version: '3.1'

services:

  db:
    image: mysql
    restart: always
    container_name: mysql_container
    hostname: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    volumes:
      - ${PWD}/prisma/setup/start.sql:/docker-entrypoint-initdb.d/start.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:${ADMINER_PORT}